# Generated by Django 5.2.12 on 2026-03-15 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.CharField(max_length=255, verbose_name='メールアドレス')),
                ('display_name', models.CharField(blank=True, max_length=100, verbose_name='表示名')),
                ('imap_host', models.CharField(max_length=255, verbose_name='IMAPホスト')),
                ('imap_port', models.IntegerField(default=993, verbose_name='IMAPポート')),
                ('smtp_host', models.CharField(max_length=255, verbose_name='SMTPホスト')),
                ('smtp_port', models.IntegerField(default=465, verbose_name='SMTPポート')),
                ('username', models.CharField(help_text='通常はメールアドレスと同じ。異なる場合のみ変更。', max_length=255, verbose_name='ログインID')),
                ('password_encrypted', models.TextField(verbose_name='パスワード（暗号化済み）')),
                ('use_ssl', models.BooleanField(default=True, verbose_name='SSL使用')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='最終同期日時')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail_accounts', to=settings.AUTH_USER_MODEL, verbose_name='オーナー')),
            ],
            options={
                'verbose_name': 'メールアカウント',
                'verbose_name_plural': 'メールアカウント',
            },
        ),
        migrations.CreateModel(
            name='MailFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='フォルダ名')),
                ('folder_type', models.CharField(choices=[('inbox', '受信トレイ'), ('sent', '送信済み'), ('draft', '下書き'), ('trash', 'ゴミ箱'), ('spam', 'スパム'), ('custom', 'カスタム')], default='custom', max_length=20, verbose_name='フォルダ種別')),
                ('remote_name', models.CharField(max_length=255, verbose_name='IMAPフォルダ名')),
                ('unread_count', models.IntegerField(default=0, verbose_name='未読数')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='mailer.mailaccount', verbose_name='メールアカウント')),
            ],
            options={
                'verbose_name': 'メールフォルダ',
                'verbose_name_plural': 'メールフォルダ',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(verbose_name='IMAP UID')),
                ('message_id', models.CharField(max_length=512, unique=True, verbose_name='Message-ID')),
                ('subject', models.CharField(blank=True, max_length=998, verbose_name='件名')),
                ('from_address', models.CharField(max_length=512, verbose_name='送信者')),
                ('to_addresses', models.JSONField(default=list, verbose_name='宛先リスト')),
                ('cc_addresses', models.JSONField(default=list, verbose_name='CCリスト')),
                ('body_text', models.TextField(blank=True, verbose_name='本文（テキスト）')),
                ('body_html', models.TextField(blank=True, verbose_name='本文（HTML）')),
                ('is_read', models.BooleanField(default=False, verbose_name='既読')),
                ('is_starred', models.BooleanField(default=False, verbose_name='スター')),
                ('has_attachments', models.BooleanField(default=False, verbose_name='添付あり')),
                ('received_at', models.DateTimeField(verbose_name='受信日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='mailer.mailaccount', verbose_name='メールアカウント')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='mailer.mailfolder', verbose_name='フォルダ')),
            ],
            options={
                'verbose_name': 'メール',
                'verbose_name_plural': 'メール',
                'ordering': ['-received_at'],
                'unique_together': {('account', 'uid', 'folder')},
            },
        ),
    ]
