# Generated by Django 5.2.12 on 2026-03-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailaccount',
            name='ssl_verify',
            field=models.BooleanField(default=True, verbose_name='SSL証明書検証'),
        ),
    ]
