# Generated by Django 4.2.29 on 2026-03-17 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0003_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=512, verbose_name='Message-ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_labels', to='mailer.mailaccount', verbose_name='メールアカウント')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_labels', to='mailer.label', verbose_name='ラベル')),
            ],
            options={
                'verbose_name': 'メールラベル紐付け',
                'verbose_name_plural': 'メールラベル紐付け',
                'unique_together': {('account', 'message_id', 'label')},
            },
        ),
        migrations.DeleteModel(
            name='Email',
        ),
    ]
