# Generated by Django 4.2.29 on 2026-04-02 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mailer', '0006_emailclassification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassifySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='有効')),
                ('hour', models.IntegerField(default=8, verbose_name='実行時（時）')),
                ('minute', models.IntegerField(default=0, verbose_name='実行時（分）')),
                ('weekdays', models.JSONField(blank=True, default=list, verbose_name='曜日指定（空=毎日）')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='最終実行日時')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classify_schedule', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'AI仕分けスケジュール',
                'verbose_name_plural': 'AI仕分けスケジュール',
            },
        ),
    ]
