# Generated by Django 4.2.29 on 2026-04-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0010_emailcache'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailcache',
            new_name='mailer_emai_folder__370098_idx',
            old_name='mailer_emai_folder__recv_idx',
        ),
        migrations.AddField(
            model_name='mailaccount',
            name='oauth2_access_token',
            field=models.TextField(blank=True, verbose_name='OAuth2アクセストークン'),
        ),
        migrations.AddField(
            model_name='mailaccount',
            name='oauth2_access_token_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='アクセストークン有効期限'),
        ),
    ]
