# Generated by Django 4.2.29 on 2026-04-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0012_fix_missing_oauth2_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcache',
            name='body_cached',
            field=models.BooleanField(default=False, verbose_name='本文キャッシュ済み'),
        ),
        migrations.AddField(
            model_name='emailcache',
            name='body_html',
            field=models.TextField(blank=True, verbose_name='本文HTML'),
        ),
        migrations.AddField(
            model_name='emailcache',
            name='body_text',
            field=models.TextField(blank=True, verbose_name='本文テキスト'),
        ),
    ]
