services:
  - type: web
    name: aimail
    runtime: python
    buildCommand: ./build.sh
    startCommand: gunicorn config.wsgi:application --timeout 300 --workers 2
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "localhost,127.0.0.1"
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "5432"
      - key: MAIL_ENCRYPTION_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: CELERY_BROKER_URL
        sync: false
      - key: CELERY_RESULT_BACKEND
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REDIRECT_URI
        sync: false
